### ISSUE TITLE
API not shutting down gracefully [JIRA: RIAK-2387]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak_api#103]
See customer ticket #13106

Reproduction steps:
- Execute operations against Riak
- Run `riak stop` on one node
- Operations on that node may return `RpbErrorResp` with the `Unknown message code:` error

This could be due to the fact that PB message handlers are de-registered from the ETS table used for lookup before all sockets are closed. What should happen is that, during shutdown, the API application cancels all in-progress Riak operations and returns an `RpbErrorResp` (with valid error code) indicating that that node is shutting down, _then_ begins un-registering handler modules.

**Comment by Basho-JIRA** [comment]
[~lbakken] Can you please coordinate with the engineering team if additional work needs to be scheduled to resolve this request? 

**_[posted via JIRA by Magnus Kessler]**_

**Comment by lukebakken** [comment]
@DSomogyi @alexmoore  - who can I contact to see if we should fix this?

**Comment by alexmoore** [comment]
@lukebakken We should talk to @JeetKunDoug tomorrow.
